;---------------------------Water----------------------------------
WaterTransparency
 StandingWaterTexture = TSWater03.tga
 StandingWaterColor = R:3 G:240 B:252
 RadarWaterColor = R:3 G:240 B:252
 TransparentWaterMinOpacity = 2
 TransparentWaterDepth = 3
End