#!/usr/bin/env python3
"""Convert a compiled Generals/Zero Hour string table (.csf) to the plain-text .str
the engine also reads.

    python3 scripts/language/csf2str.py Generals.csf > languages/<language>/generals.str
    python3 scripts/language/csf2str.py Generals.csf -o languages/russian/generals.str

Renaming a .csf to .str does NOT work, and cannot: a .csf is binary. Its text is
UTF-16LE with every byte bitwise inverted, wrapped in a table of contents. This
undoes that and writes UTF-8, which is what a .str file is now (see
languages/README.md).

Also reads a .big archive directly, since community translations ship as one:

    python3 scripts/language/csf2str.py 00RussianZH.big -o languages/russian/generals.str

It takes the first generals.csf it finds inside, whatever language folder the
archive happens to file it under -- these packs habitually put a translation at
Data\\English\\generals.csf because they were built to replace English.
"""

import argparse
import struct
import sys


def read_big_entry(path, wanted_suffix=b"generals.csf"):
    """Return the bytes of the first entry whose name ends with wanted_suffix."""
    with open(path, "rb") as f:
        if f.read(4) != b"BIGF":
            return None
        f.read(4)                                        # archive size, little-endian
        count, _first = struct.unpack(">II", f.read(8))  # the rest of the header is big-endian
        found = None
        for _ in range(count):
            offset, length = struct.unpack(">II", f.read(8))
            name = bytearray()
            while True:
                c = f.read(1)
                if c in (b"\0", b""):
                    break
                name += c
            if found is None and bytes(name).lower().endswith(wanted_suffix):
                found = (offset, length, bytes(name).decode("latin-1"))
        if found is None:
            return None
        offset, length, name = found
        print("reading %s from the archive" % name, file=sys.stderr)
        f.seek(offset)
        return f.read(length)


def parse_csf(data):
    """Yield (label, text, speech) in file order."""
    if data[:4] != b" FSC":
        raise ValueError("not a CSF file (bad magic)")
    _version, num_labels, _num_strings, _unused, _language = struct.unpack("<IIIII", data[4:24])
    pos = 24
    for index in range(num_labels):
        if data[pos:pos + 4] != b" LBL":
            raise ValueError("lost sync at label %d, offset %d" % (index, pos))
        pos += 4
        num_strings, label_len = struct.unpack("<II", data[pos:pos + 8])
        pos += 8
        # Labels are ASCII by convention; latin-1 keeps a stray byte intact rather than
        # failing, and at least one shipped translation has one.
        label = data[pos:pos + label_len].decode("latin-1")
        pos += label_len
        text, speech = "", None
        for _ in range(num_strings):
            tag = data[pos:pos + 4]
            pos += 4
            value_len = struct.unpack("<I", data[pos:pos + 4])[0]
            pos += 4
            raw = data[pos:pos + value_len * 2]
            pos += value_len * 2
            text = bytes((~b) & 0xFF for b in raw).decode("utf-16-le")
            if tag == b"WRTS":
                extra_len = struct.unpack("<I", data[pos:pos + 4])[0]
                pos += 4
                speech = data[pos:pos + extra_len].decode("latin-1")
                pos += extra_len
        yield label, text, speech
    if pos != len(data):
        print("warning: %d trailing bytes were not consumed" % (len(data) - pos), file=sys.stderr)


def escape(text):
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            continue
        else:
            out.append(ch)
    return "".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="a .csf file, or a .big archive containing one")
    ap.add_argument("-o", "--output", help="write here instead of standard output")
    args = ap.parse_args()

    with open(args.input, "rb") as f:
        head = f.read(4)
    data = read_big_entry(args.input) if head == b"BIGF" else open(args.input, "rb").read()
    if data is None:
        sys.exit("no generals.csf inside %s" % args.input)

    entries = list(parse_csf(data))

    lines = [
        "// Generated by scripts/language/csf2str.py from %s" % args.input,
        "//",
        "// Plain UTF-8. A label line, the string in double quotes, then END.",
        "// Lines starting with // are comments. Escapes: \\n \\t \\\" \\\\",
        "// See languages/README.md before editing.",
        "",
    ]
    for label, text, speech in entries:
        lines.append(label)
        lines.append('"%s"%s' % (escape(text), ("    " + speech) if speech else ""))
        lines.append("END")
        lines.append("")

    out = "\n".join(lines)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(out)
        print("wrote %d entries to %s" % (len(entries), args.output), file=sys.stderr)
    else:
        sys.stdout.write(out)


if __name__ == "__main__":
    main()
