;==============Water Settings=========================
WaterTransparency
;TransparentWaterMinOpacity = 1.0 ;opacity of water at maximum depth - 1.0 is opaque, 5 transparent.
;TransparentWaterDepth = 3.0 ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
;StandingWaterTexture = TSWater02.tga
StandingWaterColor = R:51 G:226 B:253
RadarWaterColor = R:51 G:226 B:253
End

;---------------------Weather Setting-------------------------
Weather
  SnowEnabled = yes             
  SnowTexture = exwater03.dds  
  SnowBoxDimensions = 100       
  SnowBoxDensity = 0.3            
  SnowFrequencyScaleX = 2      ;speed of side-to-side wave movement.
  SnowFrequencyScaleY = 1       ;speed of side-to-side wave movement. 
  SnowAmplitude = .9            ;amount of side-to-side movement. 
  SnowVelocity = 1.0           ;speed at which snow falls
  SnowPointSize = .2            ;scale the size of snow particles.
  SnowPointSprites = yes   ;set to "no" for point-sprite emulation.
  SnowQuadSize = .1        ;scale the size of snow particles when using point-sprite emulation.
End


