
;----------------------Radar-------------------------
Object AsianTrainStation02
  RadarPriority = NOT_ON_RADAR
End
Object BioRocketPad
  RadarPriority = NOT_ON_RADAR
End
Object CivilianBunker01
  RadarPriority = NOT_ON_RADAR
End
Object CBNukeA
  RadarPriority = NOT_ON_RADAR
End
Object CBNukeE
  RadarPriority = NOT_ON_RADAR
End
Object ChemicalFactory
  RadarPriority = NOT_ON_RADAR
End
