;---------------------------Water----------------------------------
WaterTransparency
 StandingWaterTexture = TSWater03.tga
 StandingWaterColor = R:81 G:58 B:41
 RadarWaterColor = R:81 G:58 B:41
 TransparentWaterMinOpacity = 0.8
 TransparentWaterDepth = 2.0
End