  ; SizeRateDamping = 0.75 0.90
ParticleSystem AirCarrierBowWake
  Priority = CONSTANT
  IsOneShot = No
  Shader = ALPHA
  Type = PARTICLE
  ParticleName = EXWave01.tga
  AngleZ = 0.00 0.00
  AngularRateZ = 0.00 0.00
  AngularDamping = 0.80 0.80
  VelocityDamping = 1.00 1.00
  Gravity = 0.00
  Lifetime = 100.00 100.00
  SystemLifetime = 0
  Size = 1.00 3.00
  StartSizeRate = 0.00 0.00
  SizeRate = 2.00 6.00
  SizeRateDamping = 0.35 0.70
  Alpha1 = 0.20 0.20 0
  Alpha2 = 0.00 0.00 295
  Alpha3 = 0.00 0.00 0
  Alpha4 = 0.00 0.00 0
  Alpha5 = 0.00 0.00 0
  Alpha6 = 0.00 0.00 0
  Alpha7 = 0.00 0.00 0
  Alpha8 = 0.00 0.00 0
  Color1 = R:255 G:255 B:255 0
  Color2 = R:0 G:0 B:0 0
  Color3 = R:0 G:0 B:0 0
  Color4 = R:0 G:0 B:0 0
  Color5 = R:0 G:0 B:0 0
  Color6 = R:0 G:0 B:0 0
  Color7 = R:0 G:0 B:0 0
  Color8 = R:0 G:0 B:0 0
  ColorScale = 0.00 0.00
  BurstDelay = 3.00 5.00
  BurstCount = 1.00 3.00
  InitialDelay = 0.00 0.00
  DriftVelocity = X:0.00 Y:0.00 Z:0.00
  VelocityType = ORTHO
  VelOrthoX = 1.50 1.50
  VelOrthoY = -0.30 0.30
  VelOrthoZ = 0.00 0.00
  VolumeType = LINE
  VolLineStart = X:6.00 Y:0.00 Z:2.00
  VolLineEnd = X:6.00 Y:0.00 Z:2.00
  IsHollow = No
  IsGroundAligned = Yes
  IsEmitAboveGroundOnly = No
  IsParticleUpTowardsEmitter = Yes
  WindMotion = Unused
  WindAngleChangeMin = 0.000000
  WindAngleChangeMax = 0.000000
  WindPingPongStartAngleMin = 0.000000
  WindPingPongStartAngleMax = 0.000000
  WindPingPongEndAngleMin = 0.000000
  WindPingPongEndAngleMax = 0.000000
End


ParticleSystem DrainPipeWaterRipples
  Priority = CRITICAL
  IsOneShot = No
  Shader = ADDITIVE
  Type = PARTICLE
  ParticleName = EXShockWav.tga
  AngleZ = -20.00 20.00
  AngularRateZ = 0.00 0.00
  AngularDamping = 0.00 0.00
  VelocityDamping = 0.20 0.20
  Gravity = 0.00
  Lifetime = 50.00 50.00
  SystemLifetime = 0
  Size = 8.00 12.00
  StartSizeRate = 0.00 0.00
  SizeRate = 1.00 2.00
  SizeRateDamping = 0.99 0.99
  Alpha1 = 0.00 0.00 0
  Alpha2 = 1.00 1.00 0
  Alpha3 = 1.00 1.00 0
  Alpha4 = 0.00 0.00 0
  Alpha5 = 0.00 0.00 0
  Alpha6 = 0.00 0.00 0
  Alpha7 = 0.00 0.00 0
  Alpha8 = 0.00 0.00 0
  Color1 = R:39 G:43 B:30 0
  Color2 = R:66 G:71 B:46 15
  Color3 = R:0 G:0 B:0 100
  Color4 = R:0 G:0 B:0 0
  Color5 = R:0 G:0 B:0 0
  Color6 = R:0 G:0 B:0 0
  Color7 = R:0 G:0 B:0 0
  Color8 = R:0 G:0 B:0 0
  ColorScale = 0.00 0.00
  BurstDelay = 1.00 10.00
  BurstCount = 3.00 5.00
  InitialDelay = 0.00 0.00
  DriftVelocity = X:0.00 Y:0.00 Z:0.00
  VelocityType = OUTWARD
  VelOutward = 0.00 0.00
  VelOutwardOther = 0.00 0.00
  VolumeType = CYLINDER
  VolCylinderRadius = 20.00
  VolCylinderLength = 0.00
  IsHollow = No
  IsGroundAligned = Yes
  IsEmitAboveGroundOnly = No
  IsParticleUpTowardsEmitter = No
  WindMotion = Unused
  WindAngleChangeMin = 0.149924
  WindAngleChangeMax = 0.449946
  WindPingPongStartAngleMin = 0.000000
  WindPingPongStartAngleMax = 0.785398
  WindPingPongEndAngleMin = 5.497787
  WindPingPongEndAngleMax = 6.283185
End


ParticleSystem DrainPipeWater2
  Priority = CRITICAL
  IsOneShot = No
  Shader = ALPHA
  Type = PARTICLE
  ParticleName = EXWave01.tga
  AngleZ = 0.00 7.00
  AngularRateZ = -0.50 0.50
  AngularDamping = 0.90 0.90
  VelocityDamping = 1.00 1.00
  Gravity = -0.20
  Lifetime = 25.00 25.00
  SystemLifetime = 0
  Size = 10.00 10.00
  StartSizeRate = 0.00 0.00
  SizeRate = 0.50 0.70
  SizeRateDamping = 1.02 1.06
  Alpha1 = 0.30 0.30 0
  Alpha2 = 0.10 0.10 0
  Alpha3 = 0.00 0.00 0
  Alpha4 = 0.00 0.00 0
  Alpha5 = 0.00 0.00 0
  Alpha6 = 0.00 0.00 0
  Alpha7 = 0.00 0.00 0
  Alpha8 = 0.00 0.00 0
  Color1 = R:225 G:234 B:196 20
  Color2 = R:191 G:199 B:165 30
  Color3 = R:165 G:166 B:149 40
  Color4 = R:0 G:0 B:0 0
  Color5 = R:0 G:0 B:0 0
  Color6 = R:0 G:0 B:0 0
  Color7 = R:0 G:0 B:0 0
  Color8 = R:0 G:0 B:0 0
  ColorScale = 0.00 0.00
  BurstDelay = 1.00 1.00
  BurstCount = 10.00 10.00
  InitialDelay = 0.00 50.00
  DriftVelocity = X:0.00 Y:0.00 Z:0.00
  VelocityType = ORTHO
  VelOrthoX = -0.30 0.30
  VelOrthoY = -3.00 -7.00
  VelOrthoZ = 0.00 0.00
  VolumeType = LINE
  VolLineStart = X:10.00 Y:-10.00 Z:1.00
  VolLineEnd = X:-10.00 Y:-10.00 Z:1.00
  IsHollow = No
  IsGroundAligned = No
  IsEmitAboveGroundOnly = No
  IsParticleUpTowardsEmitter = No
  WindMotion = Unused
  WindAngleChangeMin = 0.149924
  WindAngleChangeMax = 0.449946
  WindPingPongStartAngleMin = 0.000000
  WindPingPongStartAngleMax = 0.785398
  WindPingPongEndAngleMin = 5.497787
  WindPingPongEndAngleMax = 6.283185
End

Object FirestormTestObject
 RemoveModule ModuleTag_01
 AddModule
  Draw = W3DModelDraw ModuleTag_Draw01
    ConditionState = NONE
      Model = NONE
      ParticleSysBone      = NONE BlueLight
    End
  End
 End
 KindOf = ALWAYS_VISIBLE INERT
End

Object ParticleFXTestObject
 RemoveModule ModuleTag_01
 AddModule
  Draw = W3DModelDraw ModuleTag_Draw01
    ConditionState = NONE
      Model = NONE
      ParticleSysBone      = NONE AirCarrierBowWake
    End
  End
 End
 KindOf = ALWAYS_VISIBLE INERT
End

Object NukeTestObject
 RemoveModule ModuleTag_01
 AddModule
  Draw = W3DModelDraw ModuleTag_Draw01
    ConditionState = NONE
      Model = NONE
      ParticleSysBone      = NONE DrainPipeSplash
      ParticleSysBone      = NONE DrainPipeWaterRipples
      ; ParticleSysBone      = NONE DamMist
    End
  End
 End
 KindOf = ALWAYS_VISIBLE INERT
End

Object AttackHint
 RemoveModule ModuleTag_01
 AddModule
  Draw = W3DModelDraw ModuleTag_Draw01
    ConditionState = NONE
      Model = NONE
      ParticleSysBone      = NONE RedLight
    End
  End
 End
 KindOf = ALWAYS_VISIBLE INERT
End

Object SandbagWall
 RemoveModule ModuleTag_01
 AddModule
  Draw = W3DModelDraw ModuleTag_Draw01
    ConditionState = NONE
      Model = NONE
      ParticleSysBone      = NONE DrainPipeWater2
    End
  End
 End
 KindOf = ALWAYS_VISIBLE INERT
End

Object SelectIcon
 RemoveModule ModuleTag_01
 AddModule
  Draw = W3DModelDraw ModuleTag_Draw01
    ConditionState = NONE
      Model = NONE
      ParticleSysBone      = NONE MistField
    End
  End
 End
 KindOf = ALWAYS_VISIBLE INERT
End

;------------------------------------------------------------------------------
Object GreekRuin01
  KindOf = STRUCTURE IMMOBILE IGNORED_IN_GUI
End

;------------------------------------------------------------------------------
Object GreekRuin02
  KindOf = STRUCTURE IMMOBILE IGNORED_IN_GUI
End

;------------------------------------------------------------------------------
Object GreekRuin03
  KindOf = STRUCTURE IMMOBILE IGNORED_IN_GUI
End

Object GreekRuin04
  KindOf = STRUCTURE IMMOBILE IGNORED_IN_GUI
End

Object StatueAngel
  Scale 1.7
End








