;------------------------------Object Scripts------------------------------
ParticleSystem GlowingGroundParticle01
  Priority = CRITICAL
  IsOneShot = No
  Shader = ADDITIVE
  Type = PARTICLE
  ParticleName = exfthrower06.tga
  AngleZ = 0 0
  Lifetime = 180 180
  SystemLifetime = 0
  Size = 210 210
  Color1 = R:30 G:50 B:90 0
  Color2 = R:60 G:90 B:150 45
  Color3 = R:60 G:90 B:150 90
  Color4 = R:30 G:50 B:90 135
  BurstDelay = 178 178
  BurstCount = 1 1
  VelocityType = NONE
  VolumeType = LINE
  VolLineStart = X:0 Y:0 Z:2
  VolLineEnd = X:0 Y:0 Z:2
  IsGroundAligned = Yes
  IsParticleUpTowardsEmitter = Yes
End

AudioEvent n0ttws_DamDamageLoop3
  Control = random interrupt
  Sounds =  gdamlo5b gdamlo5c gdamlo5d
  Attack = gdamlo5a
  Limit = 1
  PitchShift = -5  5
  Volume = 0
  MinRange = 250
  MaxRange = 2000
  Priority = normal
  Type = world shrouded everyone
End

Object Dam
RemoveModule ModuleTag_01
RemoveModule ModuleTag_04

 AddModule
  Draw                         = W3DModelDraw ModuleTag_n0ttws01
    ConditionState             = NONE
      Model                    = CBDam   
      ParticleSysBone          = Spray01 DamOverflow
      ParticleSysBone          = Spray03 DamOverflow
      ParticleSysBone          = Spray05 DamOverflow
      ParticleSysBone          = Spray06 DamWavesOutward
    End   
    ConditionState             = DAMAGED
      Model                    = CBDam_D
      ParticleSysBone          = Spray04 DamOverflow
      ParticleSysBone          = Spray07 DamOverflow
      ParticleSysBone          = Spray08 DamOverflow
      ParticleSysBone          = WaterSpray01 WaterSpraySplash
      ParticleSysBone          = WaterSpray02 WaterSpraySplash
      ParticleSysBone          = WaterSpray03 WaterSpraySplash
      ParticleSysBone          = Spray08 DamWavesOutward
    End
    ConditionState             = REALLYDAMAGED
      Model                    = CBDam_E
      Animation                = CBDam_E.CBDam_E
      AnimationMode            = ONCE
      Flags                    = START_FRAME_FIRST
      ParticleSysBone          = WaterSpray01 WaterSpraySplash
      ParticleSysBone          = WaterSpray02 WaterSpraySplash
      ParticleSysBone          = WaterSpray04 WaterSpraySplash
      ParticleSysBone          = Spray03 DamWavesOutward
      ParticleSysBone          = WaterSprayBig01 WaterSpray
    End
    ConditionState    = RUBBLE
      Model           = CBDam_R
      Animation       = CBDam_R.CBDam_R
      AnimationMode   = ONCE
      Flags           = START_FRAME_FIRST
    End
  End
 End
  SoundAmbient = DamAmbientLoop
  SoundAmbientDamaged = DamDamageLoop1
  SoundAmbientReallyDamaged = DamDamageLoop2
  SoundAmbientRubble = n0ttws_DamDamageLoop3
End

ParticleSystem GlowingGroundParticle02
  Priority = CRITICAL
  IsOneShot = No
  Shader = ADDITIVE
  Type = PARTICLE
  ParticleName = exfthrower06.tga
  AngleZ = 0 0
  Lifetime = 180 180
  SystemLifetime = 0
  Size = 210 210
  Color1 = R:85 G:4 B:1 0
  Color2 = R:120 G:6 B:2 45
  Color3 = R:120 G:6 B:2 90
  Color4 = R:85 G:4 B:1 135
  BurstDelay = 178 178
  BurstCount = 1 1
  VelocityType = NONE
  VolumeType = LINE
  VolLineStart = X:0 Y:0 Z:2
  VolLineEnd = X:0 Y:0 Z:2
  IsGroundAligned = Yes
  IsParticleUpTowardsEmitter = Yes
End


ParticleSystem GlowingGroundParticle03
 Priority = CRITICAL
  IsOneShot = No
  Shader = ADDITIVE
  Type = PARTICLE
  ParticleName = exfthrower06.tga
  AngleZ = 0 0
  Lifetime = 180 180
  SystemLifetime = 0
  Size = 210 210
  Color1 = R:139 G:69 B:19 0
  Color2 = R:160 G:82 B:45 45
  Color3 = R:160 G:82 B:45 90
  Color4 = R:139 G:69 B:19 135
  BurstDelay = 178 178
  BurstCount = 1 1
  VelocityType = NONE
  VolumeType = LINE
  VolLineStart = X:0 Y:0 Z:2
  VolLineEnd = X:0 Y:0 Z:2
  IsGroundAligned = Yes
  IsParticleUpTowardsEmitter = Yes
End


Object CINE_Barrel01
 RemoveModule ModuleTag_01
 RemoveModule ModuleTag_02
 AddModule
  Draw = W3DModelDraw ModuleTag_Aux01
    ConditionState = NONE
      Model = NONE
	  ParticleSysBone = NONE GlowingGroundParticle01
    End
    ConditionState = DAMAGED
      Model = NONE
	  ParticleSysBone = NONE GlowingGroundParticle02
    End
    ConditionState = REALLYDAMAGED
      Model = NONE
	  ParticleSysBone = NONE GlowingGroundParticle03  ;Disco party
    End
  End
  Body              = HighlanderBody ModuleTag_Aux02
    MaxHealth       = 1000
    InitialHealth   = 1000
  End
 End
 KindOf = INERT NO_COLLIDE
  ArmorSet
    Conditions = NONE
    Armor = InvulnerableArmor
  End
End

Object CINE_Barrel02
 RemoveModule ModuleTag_01
 RemoveModule ModuleTag_02
 AddModule
  Draw = W3DModelDraw ModuleTag_Aux01
    ConditionState = NONE
      Model = NONE
      ParticleSysBone = NONE MapWaterWave
    End
  End
  Body              = HighlanderBody ModuleTag_Aux02
    MaxHealth       = 1000
    InitialHealth   = 1000
  End
 End
 KindOf = INERT NO_COLLIDE
  ArmorSet
    Conditions = NONE
    Armor = InvulnerableAllArmor
  End
End

;------------------------Radar------------------------------------
Object GermanTownHouse2
  RadarPriority = NOT_ON_RADAR
End
Object GermanTownHouse1
  RadarPriority = NOT_ON_RADAR
End
Object GermanPub02
  RadarPriority = NOT_ON_RADAR
End
Object GermanPub01
  RadarPriority = NOT_ON_RADAR
End
Object GermanCotage01
  RadarPriority = NOT_ON_RADAR
End
;------------------------------Object Scale------------------------------

Object StatueRoman
  KindOf = -STICK_TO_TERRAIN_SLOPE
End
Object StatueRoman
  Scale 1.5
End


;------------------------------Water Scripts------------------------------
Object ParticleTestObject
 RadarPriority = NOT_ON_RADAR
 ReplaceModule ModuleTag_01
  Draw                = W3DModelDraw ModuleTag_01_Override
    ConditionState    = NONE ;100%
      Model           = NONE
      ParticleSysBone = WaterSpray01 DamMist
      ParticleSysBone = WaterSpray02 DamMist
    End
    ConditionState    = DAMAGED ;50%
      Model           = NONE
      ParticleSysBone = WaterSpray01 WaterSpraySplash
      ParticleSysBone = WaterSpray02 WaterSpraySplash
      ParticleSysBone = WaterSpray03 WaterSpraySplash

    End
    ConditionState    = REALLYDAMAGED ;25%
      Model           = NONE
      ParticleSysBone = WATERSPOUT DrainPipeWater1
      ParticleSysBone = WATERSPOUT DrainPipeWater2
    End
    ConditionState    = RUBBLE ;Dead
      Model           = NONE
    End
  End
 End
End
;---------------------------Water----------------------------------
WaterTransparency
 StandingWaterColor = R:33 G:141 B:177
 RadarWaterColor = R:33 G:141 B:177
 TransparentWaterMinOpacity = 0.3
 TransparentWaterDepth = 0.1
End

;----------------------Weather settings-----------------------

